name: merlino
description: ""
version: 1.0.0
homepage: https://github.com/dbbd59/merlino

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  args: ^2.3.1
  glob: ^2.1.1
  interact: ^2.1.1
  io: ^1.0.3
  mason: ^0.0.1-dev.58
  meta: ^1.8.0
  path: ^1.8.3
  usage: ^4.1.0

dev_dependencies:
  build_runner: ^2.3.3
  ficcanaso: ^5.0.0
